name: Checks
on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - 'master'

defaults:
  run:
    shell: bash

env:
  NODE_OPTIONS: '--no-warnings'
  NEXT_TELEMETRY_DISABLED: '1'
  ACTIONS_RUNNER_DEBUG: true

jobs:
  checks:
    name: Lint/Typecheck/Build/Test
    runs-on: ['ubuntu-latest']
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4

      - name: '🐰 Setup Bun'
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 'latest'

      - name: 'Setup Biome'
        uses: biomejs/setup-biome@v1
        with:
          version: 'latest'

      - name: 'Lint'
        run: biome ci .

      - name: 'Install Dependencies'
        run: bun install --frozen-lockfile

      - name: 'Type Check'
        run: bun typecheck

      - name: 'Build'
        run: bun run build

      - name: 'Test'
        run: bun run test -- --run
