name: Release

permissions:
  contents: write

on:
  push:
    branches: ['main', 'next']

defaults:
  run:
    shell: bash

concurrency: ${{ github.workflow }}-${{ github.ref }}

env:
  NODE_OPTIONS: '--no-warnings'
  NEXT_TELEMETRY_DISABLED: '1'
  ACTIONS_RUNNER_DEBUG: true

jobs:
  release:
    name: 'Release'
    runs-on: ['ubuntu-latest']
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v4

      - name: 'Setup pnpm'
        uses: pnpm/action-setup@v3
        with:
          version: 'latest'

      - name: 'Setup Node.js'
        uses: actions/setup-node@v4
        with:
          cache: 'pnpm'
          node-version: 'lts/*'
          registry-url: 'https://registry.npmjs.org'

      - name: 'Install Dependencies'
        run: pnpm install --frozen-lockfile

      - name: 'Changesets'
        id: changesets
        uses: changesets/action@v1
        with:
          publish: pnpm release
          version: pnpm dlx bun ${{github.workspace }}/scripts/changeset-update-version.ts
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
